<?php
/** @var $block \Aheadworks\Layerednav\Block\Navigation */
/** @var \Aheadworks\Layerednav\ViewModel\Navigation $viewModel */
$viewModel = $block->getViewModel();
$filterRenderer = $block->getFilterRendererBlock();
// @codingStandardsIgnoreFile
?>

<?php if ($viewModel->isNeedToRender()): ?>
    <div id="layered-filter-block"
         class="block filter"
         data-role="filter-block"
         data-mage-init='{"collapsible":{
            "openedState": "active",
            "collapsible": true,
            "active": false,
            "collateral": {
                "openedState": "filter-active",
                "element": "body"
            }
         }}'>
        <div id="aw-layered-nav-popup"
             class="aw-layered-nav-popover aw-layered-nav-popover"
             data-role="aw-layered-nav-popover"
             data-mage-init='{"awLayeredNavPopover": {
                "filtersContainer": "#layered-filter-block",
                "isPopoverDisabled": <?= /* @noEscape */ \Zend_Json::encode($viewModel->isPopoverDisabled()) ?>,
                "hasActiveFilters": <?= /* @noEscape */ \Zend_Json::encode($viewModel->hasActiveFilters()) ?>}}'>
            <div class="aw-layered-nav-popover__content">
                <div id="aw-layered-nav-popover__items" data-role="items-count-container" class="aw-layered-nav-popover__items"></div>
                <div class="aw-layered-nav-popover__loader"><div class="aw-layered-nav-popover__loader-itself"></div></div>
                <div class="aw-layered-nav-popover__action">
                    <button data-role="show-button" class="action primary show-button"><?= $block->escapeHtml(__('Show')) ?></button>
                </div>
            </div>
        </div>
        <div class="aw-layered-nav-overlay"></div>
        <div class="block-content filter-content">
            <div class="button-list aw-layered-nav-popover__action"
                 data-role="aw-layered-nav-actions"
                 data-mage-init='{"awLayeredNavFilterActions": {}}'>
                <button data-role="close-filters" class="action primary close-filters" data-mage-init='{"awLayeredNavFilterClose": {}}'>
                    <?= __('Close Filters'); ?>
                </button>
                <button data-role="clear-button"
                        class="action primary clear-button"
                    <?php if (!$viewModel->hasActiveFilters()): ?> disabled<?php endif; ?>>
                    <?= $block->escapeHtml(__('Clear All')) ?>
                </button>
                <?php if (!$viewModel->isPopoverDisabled()): ?>
                    <button data-role="show-button"
                            class="action primary show-button<?php if (!$viewModel->hasActiveFilters()): ?> disabled<?php endif; ?>">
                            <?= $block->escapeHtml(__('Show')) ?>
                    </button>
                <?php endif; ?>
            </div>
            <?= $block->getChildHtml('modal.aw-ln.selected_filters'); ?>
            <div class="filter-options" id="narrow-by-list">
                <?php foreach ($viewModel->getFilters() as $filter): ?>
                    <?php if ($viewModel->isNeedToDisplayFilter($filter)): ?>
                        <div class="filter-options-item<?php if ($viewModel->isNeedToExpandFilter($filter, $block->getPageLayout())): ?> active<?php endif; ?>"
                             id="aw-filter-<?= $block->escapeHtml($filter->getCode()) ?>"
                             data-mage-init='{"awLayeredNavCollapse": {}}'>
                            <div data-role="title" class="filter-options-title">
                                <span class="label"><?= $block->escapeHtml(__($filter->getTitle())) ?></span>
                                <?php if ($filter->getImage()): ?>
                                    <span class="image">
                                        <img src="<?= $block->escapeUrl($filter->getImage()->getUrl()) ?>"
                                             alt="<?= $block->escapeHtml($viewModel->getImageTitle($filter)) ?>" />
                                    </span>
                                <?php endif; ?>
                                <span class="arrow"></span>
                                <span class="reset<?php if (!$viewModel->isFilterActive($filter)): ?> disabled<?php endif; ?>"
                                      data-mage-init='{"awLayeredNavFilterReset": {"params":["<?= $block->escapeHtml($filter->getCode()) ?>"]}}'>
                            </span>
                            </div>
                            <div data-role="content" class="filter-options-content"><?= /* @noEscape */ $filterRenderer ? $filterRenderer->render($filter) : '' ?></div>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
        </div>
    </div>

    <script>
        require([
            'jquery',
            'Aheadworks_Layerednav/js/filter/request/bridge',
            <?php if ($viewModel->isAjaxEnabled()): ?>
            'Aheadworks_Layerednav/js/filter/request/executor/ajax',
            <?php else: ?>
            'Aheadworks_Layerednav/js/filter/request/executor/location',
            <?php endif; ?>
            'Aheadworks_Layerednav/js/url/processor/bridge',
            <?php if ($viewModel->isNeedToUseUseAttributeValueInsteadOfId()): ?>
            'Aheadworks_Layerednav/js/url/processor/processor/value-instead-of-id',
            <?php elseif ($viewModel->isNeedToUseSubcategoriesAsAttributeValues()): ?>
            'Aheadworks_Layerednav/js/url/processor/processor/value-as-subcategory',
            <?php else: ?>
            'Aheadworks_Layerednav/js/url/processor/processor/default',
            <?php endif; ?>
            'Aheadworks_Layerednav/js/filter/data/source/ajax',
            'Aheadworks_Layerednav/js/updater',
            'Aheadworks_Layerednav/js/product-list/pager'
        ], function (
            $,
            requestBridge,
            executor,
            urlProcessorBridge,
            urlProcessor,
            ajaxDataSource,
            updater
        ) {
            requestBridge.init({executor: executor});
            urlProcessorBridge.init({processor: urlProcessor});
            ajaxDataSource.init(<?= /* @noEscape */ \Zend_Json::encode($viewModel->getDataSourceConfig()) ?>);
            $('.pages').awLayeredNavPager({});
            updater.init({});
        });
    </script>
<?php endif; ?>
