branch-defaults:
  default:
    environment: Magentoapp-env
environment-defaults:
  Magentoapp-env:
    branch: null
    repository: null
global:
  application_name: Magento App
  default_ec2_keyname: null
  default_platform: PHP 7.3 running on 64bit Amazon Linux 2
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
