<?php
/** @var \Magento\Newsletter\Block\Subscribe $block */
?>
<div class="newsletter-signup">
    <div class="newsletter-signup__content">
        <div class="newsletter-signup__content-inner">
            <div class="newsletter-signup__text-container">
                <label for="newsletter" class="newsletter-signup__text"><?= $block->escapeHtml(__('Sign up to our newsletter for inspiration and discounts')) ?></label>
            </div>
            <div class="newsletter-signup__form-container">
                <form class="form subscribe"
                    novalidate
                    action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
                    method="post"
                    data-mage-init='{"validation": {"errorClass": "mage-error"}}'
                    id="newsletter-validate-detail">
                    <div class="newsletter-signup__input-container">
                        <input name="email" type="email" id="newsletter" class="newsletter-signup__input"
                                placeholder="<?= $block->escapeHtmlAttr(__('Enter your email address')) ?>"
                                data-mage-init='{"mage/trim-input":{}}'
                                data-validate="{required:true, 'validate-email':true}"
                        />
                        <button class="newsletter-signup__button action subscribe primary"
                                title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>"
                                type="submit"
                                aria-label="Subscribe">
                            <span><?= $block->escapeHtml(__('Sign Up')) ?></span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
