<?php
/** @var \Magento\Customer\Block\Form\Login\Info $block */
?>
<?php if ($block->getRegistration()->isAllowed()) : ?>
<div class="block block-new-customer">
    <div class="block-title">
        <strong id="block-new-customer-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Don’t have an account?')) ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-new-customer-heading">
        <ul class="checklist">
            <li class="checklist__item"><?= __('Faster checkout') ?></li>
            <li class="checklist__item"><?= __('Address management') ?></li>
            <li class="checklist__item"><?= __('View order history') ?></li>
        </ul>
        <div class="actions-toolbar">
            <div class="primary">
                <a href="<?= $block->escapeUrl($block->getCreateAccountUrl()) ?>" class="action create primary"><span><?= $block->escapeHtml(__('Register Now')) ?></span></a>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
