<div class="footer-bottom">
    <div class="footer-bottom__links-container scope--footer-links-bottom">
        <?= $block->getChildHtml('footer-bottom-links'); ?>
    </div>
    <div class="footer-bottom__tagline scope--footer-tagline">
        <?= $block->getChildHtml('footer-note'); ?>
    </div>
    <div class="footer-bottom__copyright">
        <?= $block->getChildHtml('copyright'); ?>
    </div>
</div>
