<div class="footer-links scope--footer-links">
    <div class="footer-links__col">
        <?= $block->getChildHtml('footer-links-1') ?>
    </div>
    <div class="footer-links__col">
        <?= $block->getChildHtml('footer-links-2') ?>
    </div>
    <div class="footer-links__col">
        <?= $block->getChildHtml('footer-links-3') ?>
    </div>
    <div class="footer-links__col">
        <?= $block->getChildHtml('footer-links-4') ?>
    </div>
</div>
