<div class="footer-social">
    <img class="footer-social__logo" src="<?= $block->getViewFileUrl('images/logo-light.svg') ?>" alt="<?= __('Landscaping Direct') ?>" />
    <p class="footer-social__text"><?= __('Lets Get <em>Social</em>') ?></p>
    <ul class="footer-social__list">
        <li class="footer-social__item">
            <a href="#"><img src="<?= $block->getViewFileUrl('images/icons/twitter.svg') ?>" alt="<?= __('Twitter') ?>" /></a>
        </li>
        <li class="footer-social__item">
            <a href="#"><img src="<?= $block->getViewFileUrl('images/icons/facebook.svg') ?>" alt="<?= __('Facebook') ?>" /></a>
        </li>
        <li class="footer-social__item">
            <a href="#"><img src="<?= $block->getViewFileUrl('images/icons/instagram.svg') ?>" alt="<?= __('Instagram') ?>" /></a>
        </li>
        <li class="footer-social__item">
            <a href="#"><img src="<?= $block->getViewFileUrl('images/icons/pinterest.svg') ?>" alt="<?= __('Pinterest') ?>" /></a>
        </li>
    </ul>
</div>
